name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python from .python-version
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.0"

      - name: Install dependencies
        run: |
          uv install --system
          uv sync

      - name: Run tests with coverage
        run: |
          uv run --frozen pytest --cov=scripts --cov-report=xml:coverage.xml
