name: CI Workflow

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python from .python-version
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.0"

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests with coverage
        run: |
          uv run --frozen pytest --cov=scripts --cov-report=xml:coverage.xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  coverage-badge:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v5

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-xml
          path: .

      - name: Install dependencies
        run: |
          pip install xmltodict requests

      - name: Generate coverage badge via Shields.io
        run: |
          python - << 'EOF'
          import xmltodict
          from pathlib import Path
          import requests

          # Parse coverage.xml
          cov_file = Path("coverage.xml")
          with cov_file.open() as f:
              doc = xmltodict.parse(f.read())
          total_coverage = float(doc['coverage']['@line-rate']) * 100
          color = "red" if total_coverage < 50 else "yellow" if total_coverage < 80 else "brightgreen"

          # Generate badge SVG from Shields.io
          badge_url = f"https://img.shields.io/badge/coverage-{total_coverage:.1f}%25-{color}.svg"
          svg = requests.get(badge_url).text

          # Save badge
          badge_path = Path("badges/coverage.svg")
          badge_path.parent.mkdir(exist_ok=True)
          badge_path.write_text(svg)
          print(f"Coverage badge generated at {badge_path}")
          EOF

      - name: Deploy coverage badge
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_CI_WORKFLOW_TOKEN }}
          publish_dir: badges
          publish_branch: gh-pages
          commit_message: "Update coverage badge"
